const $=x=>document.getElementById(x),state={token:sessionStorage.adminToken||''};
async function api(action,payload={}){const r=await fetch(APP_CONFIG.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload,token:state.token})});const j=await r.json();if(!j.ok)throw Error(j.error);return j.data}
function msg(t,e=false){notice.textContent=t;notice.className='notice'+(e?' error':'');setTimeout(()=>notice.classList.add('hidden'),4000)}
aLoginForm.onsubmit=async e=>{e.preventDefault();try{const d=await api('adminLogin',{username:aUsername.value.trim(),password:aPassword.value});state.token=d.token;sessionStorage.adminToken=state.token;await load()}catch(x){state.token='';msg(x.message,true)}};
aLogout.onclick=()=>{sessionStorage.removeItem('adminToken');state.token='';aDash.classList.add('hidden');aLogin.classList.remove('hidden');aLogout.classList.add('hidden')};
refresh.onclick=load;
async function load(){const d=await api('adminDashboard');aLogin.classList.add('hidden');aDash.classList.remove('hidden');aLogout.classList.remove('hidden');sMembers.textContent=d.stats.totalMembers;sPending.textContent=d.stats.pendingDeposits;sFunds.textContent='₱'+(+d.stats.approvedFunds).toLocaleString();sActive.textContent=d.stats.activeMemberships;pendingBody.innerHTML=d.pending.length?d.pending.map(x=>`<tr><td>${x.fullName}<br><small>${x.email}</small></td><td>₱${(+x.amount).toLocaleString()}</td><td>${x.method}</td><td>${x.reference}</td><td>${x.proofUrl?`<a href="${x.proofUrl}" target="_blank">Open</a>`:'—'}</td><td><button class="ok" onclick="decide('${x.id}','Approved')">Approve</button> <button class="danger" onclick="decide('${x.id}','Rejected')">Reject</button></td></tr>`).join(''):'<tr><td colspan="6">No pending deposits.</td></tr>';membersBody.innerHTML=d.members.map(x=>`<tr><td>${x.fullName}<br><small>${x.email}</small></td><td>₱${(+x.walletBalance).toLocaleString()}</td><td>${x.membershipName||'None'}</td><td>${x.pointsBalance}</td><td>${x.claimCount}/${x.maxClaims}</td><td><input id="p-${x.id}" value="${x.perkNote||''}"><button onclick="perk('${x.id}')">Save</button></td></tr>`).join('')}
window.decide=async(id,status)=>{try{await api('adminDecideDeposit',{depositId:id,status});msg('Deposit '+status.toLowerCase());load()}catch(x){msg(x.message,true)}};
window.perk=async id=>{try{await api('adminSavePerk',{memberId:id,perkNote:document.getElementById('p-'+id).value});msg('Perk note saved')}catch(x){msg(x.message,true)}};
if(state.token)load().catch(()=>{});
