const PLANS=[['quartz','Quartz',500,30,30,'💎'],['amethyst','Amethyst',1000,40,50,'🔮'],['garnet','Garnet',3000,110,50,'♦️'],['aquamarine','Aquamarine',7000,240,50,'🧊'],['sapphire','Sapphire',15000,500,50,'🔷'],['emerald','Emerald',25000,858,50,'🟢']];
const $=x=>document.getElementById(x),state={token:localStorage.memberToken||'',data:null,timer:null};
async function api(action,payload={},token=''){const u=APP_CONFIG.API_URL;if(!u||u.includes('PASTE_'))throw Error('Set the Apps Script URL in config.js');const r=await fetch(u,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,payload,token})});const j=await r.json();if(!j.ok)throw Error(j.error);return j.data}
function msg(t,e=false){const n=$('notice');n.textContent=t;n.className='notice'+(e?' error':'');setTimeout(()=>n.classList.add('hidden'),4500)}
function page(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');if(id==='dashboard'&&state.token)load()}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));
function cards(target,buy=false){$(target).innerHTML=PLANS.map(p=>`<div class="card"><div style="font-size:54px">${p[5]}</div><h3>${p[1]}</h3><div class="price">₱${p[2].toLocaleString()}</div><p>${p[3]} points per claim · ${p[4]} claims</p>${buy?`<button class="full buy" data-id="${p[0]}">Activate</button>`:''}</div>`).join('');if(buy)document.querySelectorAll('.buy').forEach(b=>b.onclick=()=>buyPlan(b.dataset.id))}cards('publicPlans');
$('regForm').onsubmit=async e=>{e.preventDefault();try{await api('register',{fullName:rName.value,email:rEmail.value,mobile:rMobile.value,password:rPass.value});msg('Registration successful. Please log in.');e.target.reset();page('login')}catch(x){msg(x.message,true)}};
$('loginForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('login',{email:lEmail.value,password:lPass.value});state.token=d.token;localStorage.memberToken=d.token;nav();page('dashboard')}catch(x){msg(x.message,true)}};
$('logout').onclick=()=>{localStorage.removeItem('memberToken');state.token='';nav();page('login')};
$('depositForm').onsubmit=async e=>{e.preventDefault();try{await api('submitDeposit',{amount:+dAmount.value,method:dMethod.value,reference:dReference.value,proofUrl:dProof.value},state.token);msg('Deposit submitted for admin approval.');e.target.reset();load()}catch(x){msg(x.message,true)}};
async function buyPlan(planId){try{const p=PLANS.find(x=>x[0]===planId);if(!confirm(`Use ₱${p[2].toLocaleString()} from your wallet for ${p[1]}?`))return;state.data=await api('buyMembership',{planId},state.token);render();msg('Membership activated. The first 24-hour countdown started.')}catch(x){msg(x.message,true)}}
$('claimBtn').onclick=async()=>{try{state.data=await api('claimPoints',{},state.token);render();msg('Points claimed. A new 24-hour timer started.')}catch(x){msg(x.message,true)}};
async function load(){try{state.data=await api('memberDashboard',{},state.token);render()}catch(x){localStorage.removeItem('memberToken');state.token='';nav();page('login');msg(x.message,true)}}
function render(){const d=state.data,m=d.membership;$('welcome').textContent=`Welcome, ${d.fullName}`;$('wallet').textContent='₱'+(+d.walletBalance).toLocaleString();$('points').textContent=(+d.pointsBalance).toLocaleString();$('membership').textContent=m?m.planName:'None';$('status').textContent=m?m.status:'Inactive';cards('memberPlans',true);if(m&&m.status==='Active')document.querySelectorAll('.buy').forEach(b=>b.disabled=true);$('depositHistory').innerHTML=d.deposits.length?d.deposits.map(x=>`<div><span>${new Date(x.createdAt).toLocaleString()} · ${x.method} · ${x.reference}</span><strong>₱${(+x.amount).toLocaleString()} · ${x.status}</strong></div>`).join(''):'<p class="muted">No deposits.</p>';$('claimHistory').innerHTML=d.claims.length?d.claims.map(x=>`<div><span>${new Date(x.claimedAt).toLocaleString()}</span><strong>+${x.points}</strong></div>`).join(''):'<p class="muted">No claims.</p>';timer()}
function timer(){clearInterval(state.timer);const tick=()=>{const m=state.data?.membership;if(!m){countdown.textContent='--:--:--';claimText.textContent='Activate a membership first.';claimBtn.disabled=true;return}if(m.status==='Completed'){countdown.textContent='COMPLETED';claimText.textContent='All claims are complete.';claimBtn.disabled=true;return}const r=Math.max(0,new Date(m.nextClaimAt)-Date.now()),h=Math.floor(r/36e5),mi=Math.floor(r%36e5/6e4),s=Math.floor(r%6e4/1e3);countdown.textContent=[h,mi,s].map(x=>String(x).padStart(2,'0')).join(':');claimBtn.disabled=r>0;claimText.textContent=r?'Countdown is running.':'Ready to claim. It stays at zero until you claim.'};tick();state.timer=setInterval(tick,1000)}
function nav(){document.querySelectorAll('.member').forEach(x=>x.classList.toggle('hidden',!state.token))}nav();if(state.token)page('dashboard');
